Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission09_jazz3987.Models;
namespace Mission09_jazz3987.Components

{
	public class CartSummaryViewComponent : ViewComponent
	{
		private ShoppingCart shoppingCart { get; set; }

		public CartSummaryViewComponent(ShoppingCart temp)
		{
			shoppingCart = temp;
		}

		public IViewComponentResult Invoke()
		{
			return View(shoppingCart);
		}
	}
}

Components/CategoryViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Mission09_jazz3987.Models;

namespace Mission09_jazz3987.Components
{
	public class CategoryViewComponent : ViewComponent
	{
		private IBookstoreRepository repo { get; set; }

		public CategoryViewComponent(IBookstoreRepository temp)
		{
			repo = temp;
		}

		public IViewComponentResult Invoke()
		{
			ViewBag.SelectedCategory = RouteData?.Values["category"];

			//Get categories
			var category = repo.Books
				.Select(x => x.Category)
				.Distinct()
				.OrderBy(x => x);

			return View(category);
		}
	}
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book
<div class="card card-outline-primary m-1 p-1">
    <div class="card-body bg-faded p-1">
        <h4 class="card-title"> <!--Bootstrap 1: Card Title-->
            @Model.Title

            <span class="badge bg-primary badge-pill badge-primary rounded-pill" style="float:right;">
                <!--Had to add some weird stuff to get the dollar sign to show-->
                <small>@Model.Price.ToString("c", System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))</small>
            </span>
        </h4>
    </div>
    <h6 class="card-subtitle">Author: @Model.Author <br /></h6> <!--Bootstrap 1: Card Subtitle-->
    <div class="card-text p-1">
        Publisher: @Model.Publisher <br />
        ISBN: @Model.Isbn <br />
        Classfication: @Model.Classification <br />
        Category: @Model.Category <br />
        Number of Pages: @Model.PageCount <br />
    </div>

    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId" /> <!--Pass book to shopping cart-->
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body> <!--Apply Bootstrap-->
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">The Hilton Collection</div>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>   
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:category></vc:category>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>