Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission09_jazz3987.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission09_jazz3987.Controllers
{
    public class CheckoutController : Controller
    {
        private IPurchaseRepository repo { get; set; }

        private ShoppingCart shoppingCart { get; set; }

        public CheckoutController(IPurchaseRepository temp, ShoppingCart s)
        {
            repo = temp;
            shoppingCart = s;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (shoppingCart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = shoppingCart.Items.ToArray();
                repo.SavePurchase(purchase);
                shoppingCart.ClearCart();

                return RedirectToPage("/PurchaseComplete");
            }

            else
            {
                return View();
            }
        }
    }
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission09_jazz3987.Infrastructure;
using Mission09_jazz3987.Models;

namespace Mission09_jazz3987.Pages
{
	public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public ShoppingCart shoppingCart { get; set; }

        public string ReturnUrl { get; set; }

        public CartModel (IBookstoreRepository temp, ShoppingCart s)
        {
            repo = temp;
            shoppingCart = s;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/"; //Get Url to return to
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            // Get the right book
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            shoppingCart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl }); //Redirect to previous page
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            shoppingCart.RemoveItem(shoppingCart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Pages/Cart.cshtml
@page
@model Mission09_jazz3987.Pages.CartModel
@{
}

<h2>Your Shopping Cart</h2>

@if (@Model.shoppingCart.Items.Count() > 0)
{
    <div class="alert alert-primary" role="alert">
        @Model.shoppingCart.RecentItem added! <!--Bootstrap 2: Show alert that the selected book was added to the cart-->
    </div>
}

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.shoppingCart.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price</td>
                <td>@(i.Quantity * i.Book.Price)</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove"> <!--Needed to redirect to remove page-->
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>$@Model.shoppingCart.CalcTotal().ToString()</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Checkout" asp-action="Checkout" >Checkout</a>
</div>

Pages/PurchaseComplete.cshtml
@page
@{
}

<div class="text-center">
    <h2>Thank you for your order!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <!--Apply Bootstrap-->
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">The Hilton Collection</span>
    </div>
    <div class="row m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>